### ISSUE TITLE
 from vispy.util.transforms import perspective, translate,rotate,xrotate, yrotate, zrotate, scale ImportError: cannot import name 'xrotate'

### ISSUE THREAD

**Issue by yileichen123** [plopp/vispy-point-cloud#2]
Did you add the function xrotate, yrotate, zrotate, scale in vispy.util.transforms ? I don't find the def

**Comment by plopp** [comment]
This is awkward, sorry for a way too late reply. It seems the axis-specific rotation functions were replaced - at some point - with just the rotate function, to which you provide the axis by means of a parameter.

Docs: [Vispy 0.6 vispy.transforms.rotate](http://vispy.org/util.html#vispy.util.transforms.rotate)
